import logging

from motor.motor_asyncio import AsyncIOMotorDatabase

from app.chatbot.models import ChatSession, Citation, SessionMessage
from app.config import settings

logger = logging.getLogger("hadathana.chatbot.session")


def _collection_name() -> str:
    """Return environment-specific collection name: chat_sessions_dev or chat_sessions_prod."""
    return "chat_sessions_dev" if settings.is_dev else "chat_sessions_prod"


async def get_or_create_session(db: AsyncIOMotorDatabase, session_id: str | None) -> ChatSession:
    """Load existing session from Mongo, or return a new one (not yet saved)."""
    col = _collection_name()
    if session_id:
        doc = await db[col].find_one({"session_id": session_id})
        if doc:
            doc.pop("_id", None)
            return ChatSession(**doc)
    return ChatSession()  # new session_id auto-generated by model default


async def append_turn(
    db: AsyncIOMotorDatabase,
    session: ChatSession,
    user_content: str,
    assistant_content: str,
    citations: list[Citation],
) -> None:
    """Append user + assistant messages to session and upsert into Mongo."""
    col = _collection_name()
    session.messages.append(SessionMessage(role="user", content=user_content))
    session.messages.append(
        SessionMessage(role="assistant", content=assistant_content, citations=citations)
    )
    await db[col].update_one(
        {"session_id": session.session_id},
        {"$set": session.model_dump()},
        upsert=True,
    )
    logger.info(
        "session_updated",
        extra={
            "event": "session_updated",
            "collection": col,
            "session_id": session.session_id,
            "turns": len(session.messages) // 2,
        },
    )
